fix/ tournament no region
fnbrjs/fnbr.js pull request #595
Opened 2022-10-13 06:12 UTC by Artlfmj

2022-10-15 20:05 UTC, Artlfmj commented
Back to draft due to issue

2022-10-25 19:36 UTC, xNocken requested changes

2022-10-25 19:36 UTC, xNocken commented on src/structures/TournamentManager.ts
> +    params.append('teamAccountIds', this.client.user?.id!);
this is not required for this endpoint

2022-10-25 19:36 UTC, xNocken commented on src/structures/TournamentManager.ts
> +    const tournaments = await this.client.http.sendEpicgamesRequest(true, 'GET',
the url here seems to be wrong. it uses events-public-service-prod.ol.epicgames.com but should use events-public-service-live.ol.epicgames.com

2022-10-29 15:53 UTC, merged