[Fix] Epic moved the Chat system from xmpp to eos connect and its own api
fnbrjs/fnbr.js pull request #776
Opened 2024-07-25 18:32 UTC by LeleDerGrasshalmi

Fixes #775

2024-07-25 18:51 UTC, tnfAngel requested changes

2024-07-25 18:51 UTC, tnfAngel commented on resources/structs.ts
> +      type: string; // i.e. 'party
smol typo

2024-07-25 18:56 UTC, LeleDerGrasshalmi commented on resources/structs.ts
> +      type: string; // i.e. 'party
noone even sees that lol

2024-07-25 19:05 UTC, Krowe-moh commented on src/stomp/EOSConnect.ts
> +              'Epic-Connect-Device-Id': '',
hm?

2024-07-25 19:10 UTC, LeleDerGrasshalmi commented on src/stomp/EOSConnect.ts
> +              'Epic-Connect-Device-Id': '',
what=?

2024-07-25 20:29 UTC, tnfAngel approved these changes
I have tested the changes and everything seems to works correctly. For those who upgrade, please note that there is now a length limit of 256 characters when sending a message.

Hoping this great PR gets merged.

2024-07-25 22:20 UTC, AntogamerYT commented
![image](https://github.com/user-attachments/assets/44fa0a6e-0e5d-4de5-ba3e-6293474898b1)


Works 👍🏻 though it throws an error when the bot is alone in the party:

```js
                    throw new EpicgamesAPIError_1.default(err.response.data, config, err.response.status);
                          ^

EpicgamesAPIError: User [REDACTED] is not member of the conversation
```
(REDACTED being the bot's accountId)

2024-07-26 16:26 UTC, LeleDerGrasshalmi commented
hi @AntogamerYT, the latest update should now throw a `PartyChatConversationNotFound` error when there are no other party members.

2024-07-26 20:51 UTC, ThisNils requested changes
Looks good!
One small change request 🙂

2024-07-26 21:04 UTC, LeleDerGrasshalmi commented on src/exceptions/PartyChatConversationNotFound.ts
> +class PartyChatConversationNotFound extends Error {
i did change it already in the previous commit, seems like your comment was added on a outdated commit

2024-07-26 21:06 UTC, ThisNils approved these changes

2024-08-03 01:24 UTC, merged